core/urls.py
from django.urls import path, include
from .views import (
    IndexView,
    EventoCreateView,
    EventoListView,
    EventoUpdateView,
    EventoDeleteView
)


urlpatterns = [

    path('', IndexView.as_view(), name='index'),
    path('eventos/', EventoListView.as_view(), name='eventos'),
    path('eventos/new/', EventoCreateView.as_view(), name='eventos-create'),
    path('eventos/update/<int:pk>', EventoUpdateView.as_view(), name='eventos-update'),
    path('eventos/delete/<int:pk>', EventoDeleteView.as_view(), name='eventos-delete'),
]

easy1/urls.py
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('core.urls')),
                  path('users/', include('users.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.AdminSite.site_header = '2Easy-Events'
admin.AdminSite.site_title = 'Admin Panel'
admin.AdminSite.index_title = 'Administração 2Easy-Events'

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    UserCreateView,
    UserProfileView,
    UserUpdateView,
)

urlpatterns = [

    path('register/', UserCreateView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('<int:pk>/profile_update/', UserUpdateView.as_view(), name='profile-update'),
    ]

users/models.py
import uuid
from django.db import models
from stdimage.models import StdImageField
from django.contrib.auth.models import (
    AbstractUser,
    BaseUserManager,
)


def get_file_path(_instace, filename):
    ext = filename.split('.')[-1]
    filename = f'{uuid.uuid4()}.{ext}'
    return filename


class UserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, email, username, password, **extra_fields):
        if not email:
            raise ValueError('O E-mail é Obrigatório')
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            username=username,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, username, password, **extra_fields)

    def create_superuser(self, email, username, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser precisa ter is_superuser=True')

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser precisa ter is_staff=True')

        return self._create_user(email, username, password, **extra_fields)


class CustomUser(AbstractUser):
    GENDER_CHOICES = (
        ('Masculino', 'Masculino'),
        ('Feminino', 'Feminino'),
        ('Não Binário', 'Não Binário'),
    )
    email = models.EmailField('E-mail', unique=True)
    first_name = models.CharField('Nome', max_length=50)
    last_name = models.CharField('Sobrenome', max_length=50)
    born = models.DateField('Data de Nascimento', null=True)
    genero = models.CharField('Gênero', max_length=50, choices=GENDER_CHOICES)
    fone = models.CharField('Telefone', max_length=15)
    city = models.CharField('Cidade', max_length=30)
    uf = models.CharField('UF', max_length=30)
    is_staff = models.BooleanField('Membro da Equipe', default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'fone', 'city', 'uf']

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.email

    objects = UserManager()


class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    userCompany = models.OneToOneField
    imagem = StdImageField('Imagem', upload_to=get_file_path, default='default.jpg',
                          variations={'thumb': {'width': 150, 'height': 150, 'crop': True}})

    def __str__(self):
        return f'{self.user.username}'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from bootstrap_datepicker_plus import DatePickerInput

from .models import CustomUser, Profile


class CustomUserCreateForm(UserCreationForm, forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = [
            'email',
            'first_name',
            'last_name',
            'born',
            'genero',
            'fone',
            'city',
            'uf',
        ]
        widgets = {'born': DatePickerInput(format='%d/%m/%Y')}
        labels = {'username': 'Usuário'}

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.username = self.cleaned_data['email']
        user.is_cliente = True

        if commit:
            user.save()
        return user


class CustomUserChangeForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'born', 'fone', 'city', 'uf']
        widgets = {'born': DatePickerInput(format='%d/%m/%Y')}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['imagem']

users/views.py
from django.shortcuts import redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.views.generic import (
    CreateView,
    UpdateView,
    TemplateView,
)
from .forms import (
    CustomUserCreateForm,
    CustomUserChangeForm,
    ProfileChangeForm,
)
from .models import CustomUser


class UserCreateView(CreateView):
    model = CustomUser
    form_class = CustomUserCreateForm
    template_name = 'register.html'
    success_url = reverse_lazy('register')

    def form_valid(self, form):
        messages.success(self.request, f'Conta Criada com Sucesso!!')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Não foi possivel Criar a Conta')
        return super(UserCreateView, self).form_invalid(form)


class UserProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'profile.html'


class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserChangeForm
    second_form_class = ProfileChangeForm
    template_name = 'profile_update.html'
    success_url = reverse_lazy('profile')

    def post(self, request, *args, **kwargs):
        form = CustomUserChangeForm(request.POST, instance=request.user)
        form2 = ProfileChangeForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            messages.success(request, f'Perfil Atualizado com Sucesso!')
            return redirect('profile')
        else:
            form = CustomUserChangeForm(instance=request.user)
            form2 = ProfileChangeForm(instance=request.user.profile)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(instance=self.request.user.profile)
        return context

    def form_valid(self, form, *args, **kwargs):
        messages.success(self.request, f'Perfil Atualizado com Sucesso!!')
        return super(UserUpdateView, self).form_valid(form, *args, **kwargs)

    def test_func(self):
        customuser = self.get_object()
        if self.request.user.pk == customuser.pk:
            return True

        return False

users/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Entrar{% endblock %}

{% block content %}

    <!-- Navigation Start -->
    {% include 'navbar_register.html' %}

<section id="section-login">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 mx-auto">
                <form method="post">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Entrar</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <div class="d-flex justify-content-end">
                            <button class="btn btn-primary btn-lg btn-block" type="submit">Entrar</button>
                        </div>
                    </div>
                </form>
                <div class="border-top pt-3">
                    <small class="texte-muted">
                        Ainda não tem uma Conta?<a class="ml-2" href="{% url 'register' %}">Registre-se</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

users/templates/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Sair{% endblock %}

{% block content %}
    <!-- Navigation Start -->
    {% include 'navbar_register.html' %}
    <!-- Header Start -->
    {% include 'header.html' %}

<section id="section-logout">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 mx-auto">
                <h2>DESCONECTADO</h2>
                <div class="border-top pt-3">
                    <small class="texte-muted">
                        Você foi desconectado, deseja entrar novamente?<a class="ml-2" href="{% url 'login' %}">Entrar</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

users/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Perfil{% endblock %}

{% block content %}
    <!-- Navigation Start -->
    {% include 'navbar_register.html' %}
    <!-- Navigation End -->
    {% include 'header.html' %}
<section id="section-profile">
    <div class="container">
        <div class="row">
            <div class="col">
                <legend class="border-bottom mb-4">
                    <h2>Informações Pessoais.</h2>
                </legend>
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
            </div>
            <br>
            <div class="col-12">
                <img src="{{ user.profile.imagem.thumb.url }}" alt="Avatar" width="150" height="150">
                <br><br>
                <h4>#{{ user.id }}</h4>
                <h4>{{ user.get_full_name }}</h4>
                <h4>{{ user.born }}</h4>
                <h4>{{ user.email }} </h4>
                <h4>{{ user.city }}, {{ user.uf }} </h4>
                <br>
                <a class="btn btn-primary" href="{% url 'profile-update' user.id %}">Editar</a>
                <button type="button" class="btn btn-danger">Resetar Senha</button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

users/templates/profile_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Editar Perfil{% endblock %}

{% block content %}
    <!-- Navigation Start -->
    {% include 'navbar_register.html' %}
    <!-- Navigation End -->

<section id="section-register">
    <div class="container">
        <div class="row">
            <div class="col-5 mx-auto">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Informações Pessoais.</legend>

                        {{ form.media }}
                        {{ form|crispy }}
                        {{ form2|crispy }}

                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Salvar</button>
                        <a class="btn btn btn-danger btn-lg btn-block" href="{% url 'profile' %}">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

<script>
   $(document).ready(function(){
   $('#id_fone').phoneBrazil();
   $('.class-phone').phoneBrazil();
   $('input[name=phone]').phoneBrazil();
});
</script>
{% endblock %}

users/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Registre-se{% endblock %}

{% block content %}

    <!-- Navigation Start -->
    {% include 'navbar_register.html' %}
    <!-- Navigation End -->
{% if user.is_anonymous %}
<section id="section-register">
    <div class="container">
        <div class="row">
            <div class="col-lg-5 mx-auto">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Cadastre-se</legend>

                        {{ form.media }}
                        {{ form|crispy }}

                    </fieldset>
                    <div class="form-group">
                        <div class="d-flex justify-content-center">
                            <button class="btn btn-primary btn-lg btn-block" type="submit">Registrar</button>
                        </div>
                    </div>
                </form>
                <div class="border-top pt-3">
                    <small class="texte-muted">
                        Ja tem uma Conta?<a class="ml-2" href="{% url 'login' %}">Entrar</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</section>
{% else %}
{% include 'header.html' %}
<section id="section-logout">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 mx-auto">
                <h2>OPS! VOCÊ JA ESTA AUTENTICADO</h2>
                <div class="border-top pt-3">
                    <small class="texte-muted">
                        Você ja possui um registro. Gostaria de ir para Eventos?<a class="ml-2" href="{% url 'eventos' %}">Eventos</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</section>
{% endif %}
<script>
   $(document).ready(function(){
   $('#id_fone').phoneBrazil();
   $('.class-phone').phoneBrazil();
   $('input[name=phone]').phoneBrazil();
});
</script>
{% endblock %}